server:
  port: 8081
  servlet:
    context-path: /b-path

spring:
  application:
    name: b-service

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
