apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
data:
  application.yml: |-
    server:
      port: {{ .Values.service.server.port }}
      servlet:
        context-path: {{ .Values.service.server.servlet.contextPath }}
    spring:
      application:
        name: {{ .Chart.Name }}
      config:
        import: {{ .Values.service.config.import }}
    management:
      endpoint:
        health:
          enabled: {{ .Values.service.management.endpoint.health.enabled }}
        info:
          enabled: {{ .Values.service.management.endpoint.info.enabled }}
        restart:
          enabled: {{ .Values.service.management.endpoint.restart.enabled }}
