apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replications.desire }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "common.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image.registry" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.service.server.port }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.server.port }}
            successThreshold: {{ .Values.service.readinessProbe.successThreshold }}
            initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.service.readinessProbe.failureThreshold }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.server.port }}
            initialDelaySeconds: {{ .Values.service.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.service.livenessProbe.failureThreshold }}
      restartPolicy: {{ .Values.service.restartPolicy }}

