apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{ include "common.labels" .}}
spec:
  replicas: {{ .Values.replications.desire }}
  selector:
    matchLabels:
      {{ include "common.labels" .}}
  template:
    metadata:
      labels:
        {{ include "common.labels" .}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image.registry" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.service.server.port }}
