  {{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.name" . }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- if .Values.strategy.canary.enabled }}
  annotations:
    {{- include "ingress.canary.annotations" . | indent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
        - path: /(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "deployment.name" . }}
              port:
                number: 8083

{{- end -}}
