apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.name" . }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.server.port }}
      protocol: TCP
      targetPort: {{ .Values.service.server.port }}
      name: http
  selector:
    {{- include "service.selector.active" . | indent 4 }}
