image:
  repository: trucnguyen301197
  prefix: helm
service:
  name: b-service
  namespace: practice-helm
  server:
    port: 80
    servlet:
      contextPath: /b-path
  config:
    import: kubernetes
  management:
    endpoint:
      health:
        enabled: true
      info:
        enabled: true
      restart:
        enabled: true

  testing:
    something: something-ahihi

  readinessProbe:
    successThreshold: 3
    initialDelaySeconds: 3
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 3
    periodSeconds: 2
    failureThreshold: 2
  restartPolicy: Always
  terminationGracePeriodSeconds: 60

replications:
  desire: 1

ingress:
  enabled: false
  hostName: practice.info
  annotations:
    nginx.ingress.kubernetes.io/canary: true
    nginx.ingress.kubernetes.io/canary-weight: 20

strategy:
  type: RollingUpdate
  includeService: true
  rollingUpdate:
    maxSurge: 1 # Max number of pods create one time - default 25%
    maxUnavailable: 0 # Max number of pods offline during rollout
  canary:
    enabled: false
    namePrefix: canary
    weight: 20

